"""Mixin 宿主协议定义 — 每个 Mixin 声明自己需要的 self 属性/方法。

用法（仅类型检查时生效，运行时零开销）：

    from __future__ import annotations
    from typing import TYPE_CHECKING
    if TYPE_CHECKING:
        from _protocols import CloudHost

    class CloudMixin:
        '''...'''
        # mypy: self 满足 CloudHost 协议

供 IDE 自动补全 / mypy 静态检查 / AI 理解上下文。
"""

from __future__ import annotations

import tkinter as tk
from tkinter import ttk
from typing import Protocol, runtime_checkable


# ── 前向声明（避免循环导入） ──

class _SteamAccount(Protocol):
    friend_code: str
    persona_name: str
    def get(self, key: str, default: object = ...) -> object: ...

class _SteamNotesManager(Protocol):
    def read_notes(self, app_id: str) -> dict: ...
    def create_note(self, app_id: str, title: str, content: str) -> None: ...
    def list_all_games(self) -> list[dict]: ...
    def is_dirty(self, app_id: str) -> bool: ...
    def dirty_count(self) -> int: ...
    def cloud_upload(self, app_id: str) -> bool: ...
    def cloud_upload_all_dirty(self) -> tuple[int, int]: ...
    def scan_ai_notes(self) -> dict: ...

class _CollectionsCore(Protocol):
    def load_json(self) -> dict | None: ...
    def get_all_collections_with_refs(self, data: dict) -> list[dict]: ...

class _ConfigManager(Protocol):
    pass

class _CEFBridge(Protocol):
    def is_connected(self) -> bool: ...
    def disconnect(self) -> None: ...

class _CloudUploader(Protocol):
    initialized: bool


# ═══════════════════════════════════════════════════════════════════
#  Per-Mixin Host Protocols
# ═══════════════════════════════════════════════════════════════════

@runtime_checkable
class CloudHost(Protocol):
    """ui_cloud.py — CloudMixin 所需宿主属性"""
    root: tk.Tk
    current_account: _SteamAccount
    cloud_uploader: _CloudUploader | None
    manager: _SteamNotesManager | None
    _config: dict
    _lib_tree: ttk.Treeview
    def _get_selected_app_ids(self) -> list[str]: ...
    def _save_uploaded_hashes(self) -> None: ...
    def _refresh_games_list(self) -> None: ...
    def _parse_remotecache_syncstates(self) -> dict: ...
    def _center_window(self, win: tk.Toplevel) -> None: ...


@runtime_checkable
class NotesViewerHost(Protocol):
    """ui_notes_viewer.py — NotesViewerMixin 所需宿主属性"""
    root: tk.Tk
    manager: _SteamNotesManager | None
    def _get_selected_app_id(self) -> str | None: ...
    def _refresh_games_list(self) -> None: ...
    def _center_window(self, win: tk.Toplevel) -> None: ...
    def is_app_uploading(self, app_id: str) -> bool: ...


@runtime_checkable
class InlineAIGenHost(Protocol):
    """ui_ai_inline_gen.py — InlineAIGenMixin 所需宿主属性"""
    root: tk.Tk
    manager: _SteamNotesManager | None
    _config: dict
    _game_name_cache: dict[str, str]
    _lib_tree: ttk.Treeview
    def _get_ai_tokens(self) -> list[dict]: ...
    def _get_active_token_index(self) -> int: ...
    def _get_selected_app_ids(self) -> list[str]: ...
    def is_app_uploading(self, app_id: str) -> bool: ...
    def _refresh_games_list(self) -> None: ...


@runtime_checkable
class AISearchHost(Protocol):
    """ui_ai_search.py — AISearchMixin 所需宿主属性"""
    root: tk.Tk
    _config: dict
    _config_mgr: _ConfigManager
    _game_name_cache: dict[str, str]
    _lib_all_games: list[dict]
    _lib_all_games_backup: list[dict] | None
    _collections_core: _CollectionsCore | None
    def _get_ai_tokens(self) -> list[dict]: ...
    def _get_active_token_index(self) -> int: ...
    def _ensure_collections_core(self) -> bool: ...
    def _save_and_sync(self, data: dict, backup_description: str = ...) -> None: ...
    def _ui_refresh(self) -> None: ...
    def _center_window(self, win: tk.Toplevel) -> None: ...


@runtime_checkable
class ImportExportHost(Protocol):
    """ui_import_export.py — ImportExportMixin 所需宿主属性"""
    root: tk.Tk
    manager: _SteamNotesManager | None
    _config: dict
    _games_tree: ttk.Treeview
    def _get_game_name(self, app_id: str) -> str: ...
    def _get_selected_app_id(self) -> str | None: ...
    def _refresh_games_list(self) -> None: ...
    def _center_window(self, win: tk.Toplevel) -> None: ...
    def _save_config(self, config: dict) -> None: ...


@runtime_checkable
class SettingsHost(Protocol):
    """ui_settings.py — SettingsMixin 所需宿主属性"""
    root: tk.Tk
    current_account: _SteamAccount
    manager: _SteamNotesManager | None
    _config: dict
    _config_mgr: _ConfigManager
    _collections_core: _CollectionsCore | None
    def _center_window(self, win: tk.Toplevel) -> None: ...
    def _get_ai_tokens(self) -> list[dict]: ...
    def _save_ai_tokens(self, tokens: list[dict], idx: int) -> None: ...
    def _get_active_token_index(self) -> int: ...
    def _ensure_collections_core(self) -> bool: ...
    def _ui_refresh(self) -> None: ...


@runtime_checkable
class CollectionOpsHost(Protocol):
    """ui_collection_ops.py — CollectionOpsMixin 所需宿主属性"""
    root: tk.Tk
    _collections_core: _CollectionsCore | None
    _cef_bridge: _CEFBridge | None
    _original_col_ids: set[str]
    def _ensure_collections_core(self) -> bool: ...
    def _ui_get_selected(self) -> list[dict]: ...
    def _ui_mark_dirty(self, data: dict) -> None: ...
    def _ui_refresh(self) -> None: ...
    def _save_and_sync(self, data: dict, backup_description: str = ...) -> None: ...
    def _center_window(self, win: tk.Toplevel) -> None: ...


@runtime_checkable
class CuratorHost(Protocol):
    """ui_curator.py — CuratorMixin 所需宿主属性"""
    root: tk.Tk
    _collections_core: _CollectionsCore | None
    _cef_bridge: _CEFBridge | None
    def _ensure_collections_core(self) -> bool: ...
    def _save_and_sync(self, data: dict, backup_description: str = ...) -> None: ...
    def _ui_refresh(self) -> None: ...
    def _center_window(self, win: tk.Toplevel) -> None: ...
    def show_batch_update_mapping(self, data: dict, all_cols: list,
                                   sources: dict, on_done: object,
                                   parent_to_close: tk.Toplevel | None = ...) -> None: ...


@runtime_checkable
class RecommendHost(Protocol):
    """ui_recommend.py — RecommendMixin 所需宿主属性"""
    root: tk.Tk
    _collections_core: _CollectionsCore | None
    _cef_bridge: _CEFBridge | None
    def _ensure_collections_core(self) -> bool: ...
    def _save_and_sync(self, data: dict, backup_description: str = ...) -> None: ...
    def _ui_refresh(self) -> None: ...
    def _center_window(self, win: tk.Toplevel) -> None: ...
    def show_batch_update_mapping(self, data: dict, all_cols: list,
                                   sources: dict, on_done: object,
                                   parent_to_close: tk.Toplevel | None = ...) -> None: ...


@runtime_checkable
class SteamDBHost(Protocol):
    """ui_steamdb.py — SteamDBMixin 所需宿主属性"""
    root: tk.Tk
    _collections_core: _CollectionsCore | None
    def _ensure_collections_core(self) -> bool: ...
    def _save_and_sync(self, data: dict, backup_description: str = ...) -> None: ...
    def _ui_refresh(self) -> None: ...
    def show_batch_update_mapping(self, data: dict, all_cols: list,
                                   sources: dict, on_done: object,
                                   parent_to_close: tk.Toplevel | None = ...) -> None: ...


@runtime_checkable
class BackupHost(Protocol):
    """ui_backup.py — BackupMixin 所需宿主属性"""
    root: tk.Tk
    current_account: _SteamAccount
    _collections_core: _CollectionsCore | None
    def _ensure_collections_core(self) -> bool: ...
    def _center_window(self, win: tk.Toplevel) -> None: ...


@runtime_checkable
class LibraryHost(Protocol):
    """ui_library.py — LibraryMixin 所需宿主属性"""
    root: tk.Tk
    current_account: _SteamAccount
    manager: _SteamNotesManager | None
    cloud_uploader: _CloudUploader | None
    _config: dict
    _config_mgr: _ConfigManager
    _collections_core: _CollectionsCore | None
    _cef_bridge: _CEFBridge | None
    _game_name_cache: dict[str, str]
    def _center_window(self, win: tk.Toplevel) -> None: ...
    def _get_game_name(self, app_id: str) -> str: ...
    def _refresh_games_list(self) -> None: ...
    def _get_selected_app_ids(self) -> list[str]: ...
    def is_app_uploading(self, app_id: str) -> bool: ...
    def _parse_remotecache_syncstates(self) -> dict: ...
    def _ensure_game_name_cache_fast(self) -> None: ...
    def _bg_init_game_names(self) -> None: ...
    def _on_main_search_changed(self) -> None: ...
    def personal_recommend_ui(self) -> None: ...
    def _cloud_upload_all(self) -> None: ...
    def _cloud_upload_selected(self) -> None: ...
